_target_: icenet_mp.models.EncodeProcessDecode

name: naive-unet-naive

encoders:
  latent_space: [432, 432]
  era5:
    _target_: icenet_mp.models.encoders.NaiveLinearEncoder
  float-argo:
    _target_: icenet_mp.models.encoders.NaiveLinearEncoder
  sic-icenet:
    _target_: icenet_mp.models.encoders.NaiveLinearEncoder
  sic-ssmis:
    _target_: icenet_mp.models.encoders.NaiveLinearEncoder

processor:
  _target_: icenet_mp.models.processors.UNetProcessor
  start_out_channels: 128

decoder:
  _target_: icenet_mp.models.decoders.NaiveLinearDecoder
  bounded: true
