_target_: icenet_mp.models.EncodeProcessDecode

name: cnn-unet-cnn

encoders:
  latent_space: [108, 108]
  era5:
    _target_: icenet_mp.models.encoders.CNNEncoder
    n_layers: 2
  float-argo:
    _target_: icenet_mp.models.encoders.CNNEncoder
    n_layers: 2
  sic-icenet:
    _target_: icenet_mp.models.encoders.CNNEncoder
    n_layers: 2
  sic-ssmis:
    _target_: icenet_mp.models.encoders.CNNEncoder
    n_layers: 2

processor:
  _target_: icenet_mp.models.processors.UNetProcessor

decoder:
  _target_: icenet_mp.models.decoders.CNNDecoder
  bounded: false
  n_layers: 2
