_target_: icenet_mp.models.EncodeProcessDecode

name: cnn-gsta-cnn

encoders:
  latent_space: [216, 216]
  era5:
    _target_: icenet_mp.models.encoders.CNNEncoder
    n_layers: 1
  float-argo:
    _target_: icenet_mp.models.encoders.CNNEncoder
    n_layers: 1
  sic-osisaf:
    _target_: icenet_mp.models.encoders.CNNEncoder
    n_layers: 1
  sic-ssmis:
    _target_: icenet_mp.models.encoders.CNNEncoder
    n_layers: 1

processor:
  _target_: icenet_mp.models.processors.GSTAProcessor
  hid_channels: 256
  n_blocks: 8

decoder:
  _target_: icenet_mp.models.decoders.CNNDecoder
  n_layers: 1
  mask_type: active
  norm_type: groupnorm
  restrict_range: clamp
  skip_connection:
    method: none
