_target_: icenet_mp.models.EncodeProcessDecode

name: cnn-vit-cnn

encoders:
  latent_space: [144, 144]
  era5:
    _target_: icenet_mp.models.encoders.CNNEncoder
  sic-icenet:
    _target_: icenet_mp.models.encoders.CNNEncoder

processor:
  _target_: icenet_mp.models.processors.VitProcessor

decoder:
  _target_: icenet_mp.models.decoders.CNNDecoder
  bounded: false # Whether to bound the output between 0 and 1
