_target_: icenet_mp.models.EncodeProcessDecode

name: cnn-unet-cnn

encoders:
  latent_space: [144, 144]
  era5:
    _target_: icenet_mp.models.encoders.CNNEncoder
    kernel_size: 5
    n_layers: 1
    scale_factor: 3
  float-argo:
    _target_: icenet_mp.models.encoders.CNNEncoder
    kernel_size: 5
    n_layers: 1
    scale_factor: 3
  sic-icenet:
    _target_: icenet_mp.models.encoders.CNNEncoder
    kernel_size: 5
    n_layers: 1
    scale_factor: 3
  sic-ssmis:
    _target_: icenet_mp.models.encoders.CNNEncoder
    kernel_size: 5
    n_layers: 1
    scale_factor: 3

processor:
  _target_: icenet_mp.models.processors.UNetProcessor
  start_out_channels: 128

decoder:
  _target_: icenet_mp.models.decoders.CNNDecoder
  kernel_size: 5
  mask_type: active
  n_layers: 1
  norm_type: groupnorm
  restrict_range: sigmoid
  scale_factor: 3
