_target_: icenet_mp.models.EncodeProcessDecode

name: naive-unet-naive

encoders:
  latent_space: [432, 432]
  era5:
    _target_: icenet_mp.models.encoders.NaiveLinearEncoder
  sic-icenet:
    _target_: icenet_mp.models.encoders.NaiveLinearEncoder

processor:
  _target_: icenet_mp.models.processors.UNetProcessor
  start_out_channels: 100 # Reduce number of channels to support 21 day forecasts

decoder:
  _target_: icenet_mp.models.decoders.NaiveLinearDecoder
  bounded: false # Whether to bound the output between 0 and 1
