_target_: icenet_mp.models.EncodeProcessDecode

name: piecewise-unet-piecewise

encoders:
  latent_space: [192, 192]
  era5:
    _target_: icenet_mp.models.encoders.PiecewiseEncoder
  sic-icenet:
    _target_: icenet_mp.models.encoders.PiecewiseEncoder

processor:
  _target_: icenet_mp.models.processors.UNetProcessor

decoder:
  _target_: icenet_mp.models.decoders.PiecewiseDecoder
