_target_: icenet_mp.models.EncodeProcessDecode

name: piecewise-unet-piecewise

encoders:
  latent_space: [144, 144]
  era5:
    _target_: icenet_mp.models.encoders.PiecewiseEncoder
    conv_subblocks_initial: 1
    conv_subblocks_final: 1
  float-argo:
    _target_: icenet_mp.models.encoders.PiecewiseEncoder
    conv_subblocks_initial: 1
    conv_subblocks_final: 1
  sic-icenet:
    _target_: icenet_mp.models.encoders.PiecewiseEncoder
    conv_subblocks_initial: 1
    conv_subblocks_final: 1
  sic-osisaf:
    _target_: icenet_mp.models.encoders.PiecewiseEncoder
    conv_subblocks_initial: 1
    conv_subblocks_final: 1
  sic-ssmis:
    _target_: icenet_mp.models.encoders.PiecewiseEncoder
    conv_subblocks_initial: 1
    conv_subblocks_final: 1

processor:
  _target_: icenet_mp.models.processors.UNetProcessor
  start_out_channels: 64

decoder:
  _target_: icenet_mp.models.decoders.PiecewiseDecoder
  conv_subblocks_initial: 1
  conv_subblocks_final: 1
  mask_type: active
  restrict_range: clamp
  use_final_normalisation: false
