_target_: icenet_mp.models.EncodeProcessDecode

name: piecewise-unet-piecewise

encoders:
  latent_space: [192, 192]
  era5:
    _target_: icenet_mp.models.encoders.PiecewiseEncoder
    n_conv_blocks: 1
  float-argo:
    _target_: icenet_mp.models.encoders.PiecewiseEncoder
    n_conv_blocks: 1
  sic-icenet:
    _target_: icenet_mp.models.encoders.PiecewiseEncoder
    n_conv_blocks: 1
  sic-ssmis:
    _target_: icenet_mp.models.encoders.PiecewiseEncoder
    n_conv_blocks: 1

processor:
  _target_: icenet_mp.models.processors.UNetProcessor
  start_out_channels: 64

decoder:
  _target_: icenet_mp.models.decoders.PiecewiseDecoder
  n_conv_blocks: 1
  restrict_range: clamp
  use_hann_window: true
