_target_: icenet_mp.models.EncodeProcessDecode

name: sample

encoders:
  latent_space: [128, 128]
  era5:
    _target_: icenet_mp.models.encoders.NaiveLinearEncoder
  sic-icenet:
    _target_: icenet_mp.models.encoders.NaiveLinearEncoder

processor:
  _target_: icenet_mp.models.processors.UNetProcessor
  start_out_channels: 64

decoder:
  _target_: icenet_mp.models.decoders.NaiveLinearDecoder
