_target_: icenet_mp.models.EncodeProcessDecode

name: simvp

encoders:
  latent_space: [432, 432]
  era5:
    _target_: icenet_mp.models.encoders.NaiveLinearEncoder
  float-argo:
    _target_: icenet_mp.models.encoders.NaiveLinearEncoder
  sic-icenet:
    _target_: icenet_mp.models.encoders.NaiveLinearEncoder
  sic-ssmis:
    _target_: icenet_mp.models.encoders.NaiveLinearEncoder

processor:
  _target_: icenet_mp.models.processors.SimVPProcessor
  hid_channels_spatial: 64
  hid_channels_temporal: 256
  spatial_depth: 4
  temporal_depth: 8

decoder:
  _target_: icenet_mp.models.decoders.NaiveLinearDecoder
  mask_type: active
  restrict_range: sigmoid
