---

version: 2
updates:
  # GitHub Actions
  # - .github/workflows/
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Pre-commit hooks
  # - .pre-commit-config.yaml
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
  # Python packages
  # - pyproject.toml
  - package-ecosystem: uv
    directory: "/"
    cooldown:
      default-days: 7  # only consider packages that were released at least 7 days ago
    schedule:
      interval: "weekly"
