ci:
  autoupdate_commit_msg: ":rotating_light: Fix pre-commit linting errors"
  autofix_commit_msg: ":rotating_light: Fix pre-commit linting errors"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.5"
    hooks:
      # Run the linter
      - id: ruff-check
        args: ["--select", "I", "--fix", "--show-fixes"]
        pass_filenames: true
      # Run the formatter
      - id: ruff-format
        pass_filenames: true
