[project]
site_name = "IceNet-MP"
docs_dir = "docs/src"
repo_name = "alan-turing-institute/icenet-mp"
repo_url = "https://github.com/alan-turing-institute/icenet-mp"
site_dir = "docs/_build"

# Structure
nav = [
    { "Home" = "index.md" },
    { "User Guide" = "user-guide/index.md" },
    { "API Reference" = "api/index.md" },
]

[project.theme]
variant = "classic"
features = [
    "navigation.sections",
    "navigation.top",
    "toc.integrate",
]

[[project.theme.palette]]
scheme = "default"
primary = "indigo"
accent = "indigo"

# mkdocstrings configuration
[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["icenet_mp"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
inherited_members = false
members_order = "source"
show_if_no_docstring = true
show_root_full_path = false
show_root_heading = true
show_source = false
