"""Latent-space DDPM processor.

This module provides a diffusion-based processor for the EncodeProcessDecode
pipeline. It performs denoising in the shared latent space produced by the
encoders, using v-parameterisation with `UNetDiffusion` and
`GaussianDiffusion`.

The processor supports two forecasting modes:

* Autoregressive: generates forecast steps sequentially, updating the history
  with each predicted target latent.
* Parallel: generates all forecast steps jointly in a single diffusion
  process, with forecast steps folded into the channel dimension.

Only the target-latent channels are generated by the diffusion model.
Non-target channels are not predicted; they are copied from the last history
frame and carried forward unchanged.
"""

from typing import Any

import hydra
import torch
from omegaconf import DictConfig
from torch import nn

from icenet_mp.models.diffusion import GaussianDiffusion, UNetDiffusion
from icenet_mp.types import BetaSchedule, ProcessorOutput, TensorNCHW, TensorNTCHW

from .base_processor import BaseProcessor


class DDPMProcessor(BaseProcessor):
    """Latent-space DDPM processor with v-prediction.

    Input space:
        TensorNTCHW with shape (batch_size, n_history_steps, n_latent_channels_total, latent_height, latent_width)
        - Concatenation of every encoder's latent output along the channel dimension
        - The target-latent slice is assumed to occupy channels [target_slice_start : target_slice_start + n_latent_channels_target]

    Output space:
        TensorNTCHW with shape (batch_size, n_forecast_steps, n_latent_channels_total, latent_height, latent_width)
        - Target-latent slice contains the denoised prediction from reverse diffusion
        - Non-target channels are carried forward from the last observed history frame (persistence in latent)
    """

    def __init__(  # noqa: PLR0913
        self,
        *,
        timesteps: int = 1000,
        beta_schedule: str = "cosine",
        kernel_size: int = 3,
        start_out_channels: int = 64,
        time_embed_dim: int = 256,
        dropout_rate: float = 0.1,
        normalization: str = "groupnorm",
        activation: str = "SiLU",
        use_autoregressive: bool = True,
        target_slice_start: int = 0,
        loss: DictConfig | nn.Module,
        **kwargs: Any,
    ) -> None:
        """Initialize the DDPM processor.

        Args:
            timesteps (int): Number of diffusion timesteps. Default is 1000.
            beta_schedule (str): Beta schedule used by ``GaussianDiffusion``:
                ``"cosine"`` or ``"linear"``. Default is ``"cosine"``.
            kernel_size (int): Convolution kernel size used in the conditional UNet.
            start_out_channels (int): Base number of channels in the first UNet block.
            time_embed_dim (int): Dimensionality of the diffusion timestep embedding.
            dropout_rate (float): Dropout probability applied inside the UNet blocks.
            normalization (str): Normalization layer type (e.g., "groupnorm").
            activation (str): Activation function used throughout the network (e.g., "SiLU").
            use_autoregressive (bool): Whether to use autoregressive sampling and
                one-step training. Default is True.
            target_slice_start (int): Channel offset at which the target-latent
                slice appears inside the combined latent.
                Set automatically by ``EncodeProcessDecode``.
            loss (DictConfig | nn.Module): Loss module applied to (pred_v,
                target_v). Set this to ``${loss}`` in the yaml to reuse the
                top-level configured loss.
            **kwargs: Additional arguments passed to ``BaseProcessor``.

        """
        kwargs.pop("computes_loss_in_latent_space", None)
        super().__init__(computes_loss_in_latent_space=True, **kwargs)

        # Instantiate the configured loss function.
        self.loss_fn: nn.Module = (
            loss if isinstance(loss, nn.Module) else hydra.utils.instantiate(loss)
        )

        # c_combined: total channels across all encoder latents concatenated.
        c_combined = self.data_space.channels

        # c_target: channels of the target encoder's latent output.
        c_target = self.data_space_target.channels

        # Validate that the target slice fits inside the combined latent channels.
        if target_slice_start < 0 or target_slice_start + c_target > c_combined:
            msg = (
                f"target_slice_start={target_slice_start} with target channels="
                f"{c_target} does not fit inside combined latent channels="
                f"{c_combined}."
            )
            raise ValueError(msg)

        self.timesteps = timesteps
        self.use_autoregressive = use_autoregressive

        # Where the target's channels start in the combined latent. 0 means the target encoder is listed first.
        self.target_slice_start = target_slice_start
        self.c_target = c_target
        self.c_combined = c_combined

        # UNet conditioning channels: history folded NTCHW -> NCHW.
        cond_channels = c_combined * self.n_history_steps

        # Channels the UNet denoises: c_target (AR) or n_forecast_steps * c_target (parallel, all steps folded into channels).
        diffused_channels = (
            c_target if use_autoregressive else c_target * self.n_forecast_steps
        )
        self.diffused_channels = diffused_channels

        self.model = UNetDiffusion(
            input_channels=cond_channels,
            output_channels=diffused_channels,
            timesteps=timesteps,
            kernel_size=kernel_size,
            start_out_channels=start_out_channels,
            time_embed_dim=time_embed_dim,
            normalization=normalization,
            activation=activation,
            dropout_rate=dropout_rate,
        )
        self.diffusion = GaussianDiffusion(
            timesteps=timesteps,
            beta_schedule=BetaSchedule(beta_schedule),
        )

    def rollout(
        self,
        x: TensorNTCHW,
        y: TensorNTCHW | None = None,
    ) -> ProcessorOutput:
        """Run the diffusion process in latent space.

        Dispatches between two execution paths:

        1. Training path (``y`` provided):
        - Adds noise to the encoded target latent at a random diffusion timestep.
        - Predicts v conditioned on the encoded history.
        - Returns a v-prediction loss inside ``ProcessorOutput``, computed
          by ``self.loss_fn`` (the configured loss).

        2. Inference path (``y`` is None):
        - Runs reverse diffusion from Gaussian noise conditioned on the encoded history.
        - Autoregressive or parallel depending on ``self.use_autoregressive``.

        Args:
            x (TensorNTCHW): Encoded history tensor of shape
                (B, n_history_steps, n_latent_channels_total, H, W).
            y (TensorNTCHW | None): During training: encoded target latent of
                shape (B, n_forecast_steps, n_latent_channels_target, H, W).
                Otherwise: None.

        Returns:
            ProcessorOutput:
            - prediction: (B, n_forecast_steps, n_latent_channels_total, H, W)
            - loss: v-prediction loss from ``self.loss_fn`` (training only,
                otherwise None)

        """
        if y is not None:
            return self._training_rollout(x, y)
        return self._inference_rollout(x)

    def _build_metrics_prediction(
        self, pred_x0: TensorNCHW, last_frame: TensorNCHW
    ) -> TensorNTCHW:
        """Lift the training-time x_0 estimate into an NTCHW combined-latent tensor.

        The returned tensor is only used for metrics/callbacks (the actual
        training signal is the v-prediction MSE loss). Non-target channels are
        filled with the last observed frame (persistence in latent space).

        Args:
            pred_x0 (TensorNCHW): Predicted x_0 of shape (B, C_target, H, W)
                in autoregressive mode, or (B, n_forecast_steps * C_target, H, W)
                in parallel mode.
            last_frame (TensorNCHW): Last observed history frame of shape
                (B, C_combined, H, W).

        Returns:
            TensorNTCHW: Combined-latent tensor of shape
                (B, n_forecast_steps, C_combined, H, W).

        """
        b = pred_x0.shape[0]
        h, w = last_frame.shape[-2:]

        # Restore the predicted target latent to the combined latent representation.
        if self.use_autoregressive:
            per_step = self._insert_target(last_frame, pred_x0)
            return per_step.unsqueeze(1).expand(
                b, self.n_forecast_steps, self.c_combined, h, w
            )

        # In parallel mode, the predicted x_0 is folded into channels for all forecast steps.
        pred_x0_ntchw = pred_x0.reshape(b, self.n_forecast_steps, self.c_target, h, w)

        # Repeat the last frame across forecast steps; overwrite the target slice below.
        expanded_last = (
            last_frame.unsqueeze(1)
            .expand(b, self.n_forecast_steps, self.c_combined, h, w)
            .clone()
        )
        s = self.target_slice_start
        expanded_last[:, :, s : s + self.c_target] = pred_x0_ntchw
        return expanded_last

    def _flatten_history(self, x: TensorNTCHW) -> TensorNCHW:
        """Fold the history time dimension into channels.

        Args:
            x (TensorNTCHW): History tensor of shape (B, T_hist, C, H, W).

        Returns:
            TensorNCHW: Tensor of shape (B, T_hist * C, H, W).

        """
        b, t, c, h, w = x.shape
        return x.reshape(b, t * c, h, w)

    def _slice_target(self, x: TensorNCHW) -> TensorNCHW:
        """Extract the target-latent channels from a combined-latent NCHW tensor.

        Args:
            x (TensorNCHW): Combined-latent tensor of shape (B, C_combined, H, W).

        Returns:
            TensorNCHW: Target-latent slice of shape (B, C_target, H, W).

        """
        s = self.target_slice_start
        return x[:, s : s + self.c_target]

    def _insert_target(self, base_frame: TensorNCHW, target: TensorNCHW) -> TensorNCHW:
        """Return a copy of ``base_frame`` with its target slice overwritten by ``target``.

        Used to produce a C_combined-channel prediction for the frozen decoder
        while only forecasting the target-latent slice.

        Args:
            base_frame (TensorNCHW): Combined-latent frame of shape (B, C_combined, H, W).
            target (TensorNCHW): Target-latent slice of shape (B, C_target, H, W).

        Returns:
            TensorNCHW: Combined-latent frame of shape (B, C_combined, H, W).

        """
        result = base_frame.clone()
        s = self.target_slice_start
        result[:, s : s + self.c_target] = target
        return result

    def _training_rollout(self, x: TensorNTCHW, y: TensorNTCHW) -> ProcessorOutput:
        """One training rollout using DDPM v-prediction loss.

        During training, the clean target latent is corrupted using the forward
        diffusion process by adding noise at a randomly sampled timestep. The
        model is trained to predict the corresponding v-target on the
        target-latent slice.

        Args:
            x (TensorNTCHW): Encoded history tensor of shape
                (B, n_history_steps, n_latent_channels_total, H, W).
            y (TensorNTCHW): Encoded target latent of shape
                (B, n_forecast_steps, n_latent_channels_target, H, W).

        Returns:
            ProcessorOutput:
            - prediction: (B, n_forecast_steps, n_latent_channels_total, H, W)
                Combined-latent tensor built from the predicted x_0 (target
                slice) and the last observed frame (non-target slice). Used
                only for metrics/callbacks under ``torch.no_grad``.
            - loss: v-prediction loss value computed by ``self.loss_fn``.

        Notes:
            - In autoregressive mode, the model is trained on forecast step 0
              only, matching the convention used by ``icenet_mp.models.ddpm.DDPM``.
              Multi-step forecasts come from rolling out the AR loop at inference.
            - In parallel mode, the model is trained on all forecast steps
              jointly (folded into the channel dimension).

        """
        b = x.shape[0]
        device = x.device

        # Last observed frame; its non-target channels are copied into the metrics prediction
        # (the model only predicts the target slice, so the rest is persistence).
        last_frame = x[:, -1]  # (B, C_combined, H, W)

        # History frames folded into channels for the 2D UNet.
        cond = self._flatten_history(x)  # (B, T_hist * C_combined, H, W)

        # Clean target to denoise: AR uses step 0 only; parallel folds all steps into channels.
        if self.use_autoregressive:
            # AR trains on forecast step 0 (T=0) only.
            y_flat = y[:, 0]  # (B, C_target, H, W)
        else:
            y_flat = y.reshape(b, self.n_forecast_steps * self.c_target, *y.shape[-2:])

        # Random diffusion timestep per sample.
        t = torch.randint(0, self.timesteps, (b,), device=device).long()

        # Add noise to the clean target at diffusion step t.
        noise = torch.randn_like(y_flat)
        noisy_y = self.diffusion.q_sample(y_flat, t, noise)

        # Predict the velocity conditioned on the noisy target and history.
        pred_v = self.model(noisy_y, t, cond)

        # Compute the target velocity for the sampled noise and timestep.
        target_v = self.diffusion.calculate_v(y_flat, noise, t)

        # Compute the v-prediction training loss.
        loss = self.loss_fn(pred_v, target_v)

        # Reconstruct x0 for metrics only; this is not used for training.
        with torch.no_grad():
            # calculate_v() has the same formula as the x_0 reconstruction,
            # so we reuse it by passing pred_v as x_start.
            pred_x0 = self.diffusion.calculate_v(x_start=pred_v, noise=noisy_y, t=t)
            prediction = self._build_metrics_prediction(pred_x0, last_frame)

        return ProcessorOutput(prediction=prediction, loss=loss)

    def _inference_rollout(self, x: TensorNTCHW) -> ProcessorOutput:
        """Generate a latent forecast using a reverse diffusion process.

        This method selects between two diffusion sampling strategies:

        1. Non-autoregressive (parallel) sampling:
        - The model generates the entire future sequence in a single diffusion process.
        - No temporal dependency exists between forecast steps.

        2. Autoregressive sampling:
        - Forecast steps are generated sequentially.
        - Each step is produced via an independent diffusion process.
        - The conditioning window is updated after each step to incorporate
            previously generated outputs.

        Args:
            x (TensorNTCHW): Encoded history tensor of shape
                (B, n_history_steps, n_latent_channels_total, H, W).

        Returns:
            ProcessorOutput:
            - prediction: (B, n_forecast_steps, n_latent_channels_total, H, W)
            - loss: None

        Notes:
            - The diffusion process follows v-parameterization.
            - Sampling begins from standard Gaussian noise.

        """
        if self.use_autoregressive:
            return ProcessorOutput(prediction=self._sample_autoregressive(x))
        return ProcessorOutput(prediction=self._sample_parallel(x))

    def _sample_parallel(self, x: TensorNTCHW) -> TensorNTCHW:
        """Non-autoregressive (parallel) reverse diffusion sampling.

        This method generates the entire forecast sequence in a single
        diffusion process applied to one joint output tensor. The forecast
        steps are encoded as channels in a single tensor of shape
        (B, n_forecast_steps * C_target, H, W), then reshaped back to NTCHW
        and lifted into the combined latent for the frozen decoder.

        Args:
            x (TensorNTCHW): Encoded history tensor of shape
                (B, n_history_steps, n_latent_channels_total, H, W).

        Returns:
            TensorNTCHW: Denoised forecast latent of shape
                (B, n_forecast_steps, n_latent_channels_total, H, W).

        Notes:
            - Sampling starts from Gaussian noise.
            - The model predicts v-parameterization at each diffusion step.
            - All forecast steps are denoised together as a single object.

        """
        cond = self._flatten_history(x)

        b, _, h, w = cond.shape
        device = cond.device

        y = torch.randn((b, self.n_forecast_steps * self.c_target, h, w), device=device)

        # Iteratively denoise from the final diffusion timestep to zero.
        for t_step in reversed(range(self.timesteps)):
            t = torch.full((b,), t_step, dtype=torch.long, device=device)
            pred_v = self.model(y, t, cond)
            y = self.diffusion.p_sample(y, t, pred_v)

        # Build the combined latent, keeping non-target channels persistent.
        y_ntchw = y.reshape(b, self.n_forecast_steps, self.c_target, h, w)
        last_frame = x[:, -1]  # (B, C_combined, H, W)
        combined = (
            last_frame.unsqueeze(1)
            .expand(b, self.n_forecast_steps, self.c_combined, h, w)
            .clone()
        )

        # Replace the target slice while keeping non-target channels persistent.
        s = self.target_slice_start
        combined[:, :, s : s + self.c_target] = y_ntchw
        return combined

    def _sample_autoregressive(self, x: TensorNTCHW) -> TensorNTCHW:
        """Autoregressive reverse diffusion sampling (one forecast step at a time).

        Each forecast step is generated sequentially via an independent reverse
        diffusion process. After each step, the conditioning window is updated:
        the predicted target-latent frame is appended to the history's target
        slice, and non-target channels are carried forward from the last
        observed frame (persistence in latent space).

        Args:
            x (TensorNTCHW): Encoded history tensor of shape
                (B, n_history_steps, n_latent_channels_total, H, W).

        Returns:
            TensorNTCHW: Denoised forecast latent of shape
                (B, n_forecast_steps, n_latent_channels_total, H, W),
                formed by stacking all per-step predictions along the time
                dimension and lifting into the combined latent.

        Notes:
            - Sampling at each step starts from standard Gaussian noise.
            - The model predicts v-parameterization at every diffusion timestep.
            - The history window slides forward by one frame per step, using
              the model's own prediction as the new observation of the target
              slice.

        """
        history = x.clone()  # (B, T_hist, C_combined, H, W)
        b, _, _, h, w = x.shape
        device = x.device
        all_predictions: list[TensorNCHW] = []

        for _ in range(self.n_forecast_steps):
            cond_window = history[:, -self.n_history_steps :]
            cond = self._flatten_history(cond_window)  # (B, T_hist * C_combined, H, W)

            # Start each forecast step from Gaussian noise.
            y = torch.randn((b, self.c_target, h, w), device=device)

            # Iteratively denoise from the final diffusion timestep to zero.
            for t_step in reversed(range(self.timesteps)):
                t = torch.full((b,), t_step, dtype=torch.long, device=device)
                pred_v = self.model(y, t, cond)
                y = self.diffusion.p_sample(y, t, pred_v)

            all_predictions.append(y)

            # Append the prediction to the history for the next forecast step.
            last_frame = history[:, -1]  # (B, C_combined, H, W)
            new_frame = self._insert_target(last_frame, y).unsqueeze(1)
            history = torch.cat([history, new_frame], dim=1)

        target_ntchw = torch.stack(
            all_predictions, dim=1
        )  # (B, T_fcst, C_target, H, W)
        last_frame = x[:, -1]
        combined = (
            last_frame.unsqueeze(1)
            .expand(b, self.n_forecast_steps, self.c_combined, h, w)
            .clone()
        )

        s = self.target_slice_start
        combined[:, :, s : s + self.c_target] = target_ntchw
        return combined
