defaults:
  - callbacks:
    - best_checkpoint
    - early_stopping
    - ema_weight_averaging
    - learning_rate
    - media_logging
    - metric_summary
  - lr_scheduler: default
  - multistage: default
  - optimizer: default
  - scheduler: default
  - trainer: default
  - _self_
