defaults:
  - callbacks:
    - device_stats
    - ema_weight_averaging
    - learning_rate
    - metric_summary
    - plotting
  - optimizer: default
  - scheduler: default
  - trainer: default
  - _self_
