defaults:
  - default
  - override callbacks:
    - best_checkpoint
    - early_stopping
    - ema_weight_averaging
    - learning_rate
    - media_logging
  - _self_

trainer:
  log_every_n_steps: 10
  max_epochs: 30
