defaults:
  - default
  - override callbacks:
    - best_checkpoint
    - early_stopping
    - ema_weight_averaging
    - learning_rate
    - metric_summary
    - plotting
    - loss_history
  - _self_

trainer:
  max_epochs: 10
