# =============================================================================
# Weighted BCEWithLogits Loss
# =============================================================================
# Reference: https://pytorch.org/docs/stable/generated/torch.nn.BCEWithLogitsLoss.html
#
# BCEWithLogits loss with elementwise weighting.
# Using BCEWithLogitsLoss instead of BCELoss, as it is more numerically stable.
#
# When to use:
# - Binary classification or segmentation tasks where spatial weighting is needed
# =============================================================================

_target_: icenet_mp.losses.weighted_bce_loss.WeightedBCEWithLogitsLoss