# Base config inherited by all other configs
defaults:
  - data: sample
  - evaluate: default
  - loggers:
    - wandb
  - model: naive_unet_naive
  - predict: sic-icenet-2d
  - random: default
  - train: default
  - _self_

base_path: ../base
