defaults:
  - base
  - override /data: demo
  - override /predict: sic-icenet-2d
  - _self_

# Disable decoder masking as sic-icenet targets have no associated masks
model:
  decoder:
    mask_type: null
