media_logging:
  _target_: icenet_mp.callbacks.MediaLoggingCallback
  frequency:
    number: 3 # plot exactly 3 batches equally spaced across the epoch
  make_input_plots: false
  make_static_plots: true
  make_video_plots: false
  model_name: ${model.name}
  plot_spec:
    dpi: 72
