# @package _global_
defaults:
  - /base
  - override /model: unet
  - _self_

# Reduce learning rate and increase weight decay to reduce overfitting
train:
  optimizer:
    lr: 1e-3
    weight_decay: 0.05
