# @package _global_
defaults:
  - /base
  - override /loss: huber
  - override /model: unet
  - _self_

# Custom learning rate and weight decay
train:
  optimizer:
    lr: 1e-3
    weight_decay: 0.05
