# @package _global_
defaults:
  - /base
  - override /model: dc_unet_dc
  - _self_

train:
  multistage:
    finetune:
      optimizer:
        lr: 1e-4  # set to lower than for the other stages
  optimizer:
    lr: 5e-4  # default lr (5e-3) causes chronic training instability for ResBlocks
