"""Generate the full reference configuration documentation page.

Run from the project root:

    uv run --group docs python docs/generate_config.py
"""

from pathlib import Path

from hydra import compose, initialize_config_dir
from omegaconf import OmegaConf

DOCS_DIR = Path(__file__).parent
CONFIG_DIR = str(DOCS_DIR.parent / "icenet_mp" / "config")
OUTPUT_PATH = DOCS_DIR / "src" / "api" / "config.md"

HEADER = """\
# Reference configuration

<!-- This file is auto-generated by `docs/generate_config.py` — do not edit by hand. -->

The full default configuration composed from [`icenet_mp/config/base.yaml`](https://github.com/alan-turing-institute/icenet-mp/blob/main/icenet_mp/config/base.yaml) and all its sub-configs.
This is the configuration used when you run any command without overrides.

!!! note
    Interpolation markers such as `${base_path}` are left unresolved so you can see exactly which keys reference shared values.
    Set `base_path` in your local config file to point to your data directory.

## Named model configs

The `model` section below shows the default (`naive-unet-naive`).
Alternative model configs live in `icenet_mp/config/model/` and can be selected with:

```bash
uv run imp <command> --config-name my_config  # where my_config inherits base and overrides /model
```

## Full config

"""


def main() -> None:
    with initialize_config_dir(config_dir=CONFIG_DIR, version_base=None):
        cfg = compose(config_name="base")

    OUTPUT_PATH.write_text(f"{HEADER}```yaml\n{OmegaConf.to_yaml(cfg)}```\n")
    print(f"Written to {OUTPUT_PATH.relative_to(DOCS_DIR.parent)}")


if __name__ == "__main__":
    main()
