"""Research helpers deliberately isolated from production model paths."""

from .argo_cross_attention import (
    SparseCrossAttentionConfig,
    SparseCrossAttentionEncoder,
)
from .argo_reconstruction import (
    EvaluationCase,
    EvaluationRecord,
    MeasurementNormaliser,
    ReconstructionFitSummary,
    ReconstructionTrainingConfig,
    RetentionSummary,
    ScalarSummary,
    SparseReconstructionModel,
    build_evaluation_cases,
    evaluate_interpolation,
    evaluate_reconstruction_model,
    fit_reconstruction_model,
    parameter_counts,
    summarise_records,
)
from .argo_setconv import SparseSetConvConfig, SparseSetConvEncoder
from .argo_sparse import (
    ArgoFrameColumns,
    BenchmarkMemoryHook,
    BenchmarkRepeat,
    BenchmarkResult,
    GaussianInterpolationBaseline,
    ObservationSplit,
    PaddedSparseBatch,
    RegressionMetrics,
    SparseEncoder,
    SparseObservations,
    TorchCudaMemoryHook,
    benchmark_encoder,
    benchmark_retention_levels,
    compute_regression_metrics,
    count_trainable_parameters,
    pad_sparse_observations,
    retain_observations,
    sparse_observations_from_dataframe,
    split_observations,
)
from .argo_torch import (
    TorchSparseSequenceBatch,
    latlon_to_unit_xyz,
    spherical_fourier_features,
    torch_sparse_sequence_from_observations,
)

__all__ = [
    "ArgoFrameColumns",
    "BenchmarkMemoryHook",
    "BenchmarkRepeat",
    "BenchmarkResult",
    "EvaluationCase",
    "EvaluationRecord",
    "GaussianInterpolationBaseline",
    "MeasurementNormaliser",
    "ObservationSplit",
    "PaddedSparseBatch",
    "ReconstructionFitSummary",
    "ReconstructionTrainingConfig",
    "RegressionMetrics",
    "RetentionSummary",
    "ScalarSummary",
    "SparseCrossAttentionConfig",
    "SparseCrossAttentionEncoder",
    "SparseEncoder",
    "SparseObservations",
    "SparseReconstructionModel",
    "SparseSetConvConfig",
    "SparseSetConvEncoder",
    "TorchCudaMemoryHook",
    "TorchSparseSequenceBatch",
    "benchmark_encoder",
    "benchmark_retention_levels",
    "build_evaluation_cases",
    "compute_regression_metrics",
    "count_trainable_parameters",
    "evaluate_interpolation",
    "evaluate_reconstruction_model",
    "fit_reconstruction_model",
    "latlon_to_unit_xyz",
    "pad_sparse_observations",
    "parameter_counts",
    "retain_observations",
    "sparse_observations_from_dataframe",
    "spherical_fourier_features",
    "split_observations",
    "summarise_records",
    "torch_sparse_sequence_from_observations",
]
