plotting:
  _target_: icenet_mp.callbacks.PlottingCallback
  frequency:
    number: 3 # plot exactly 3 sample batches equally space in the date range
  make_input_plots: true
  make_static_plots: true
  make_video_plots: true
  base_path: ${base_path}
